language: haskell
ghc:
  - 7.8
  - 7.6
install: cabal install happy --constraint="mtl==2.1.3.1"
script:
  - cabal install lambdabot-core/
  - cabal install lambdabot-trusted/
  - cabal install lambdabot-reference-plugins/
  - cabal install lambdabot-haskell-plugins/
  - cabal install lambdabot-irc-plugins/
  - cabal install lambdabot-misc-plugins/
  - cabal install lambdabot-novelty-plugins/
  - cabal install lambdabot-social-plugins/
  - cabal install saki-iseng-plugins/
  - cabal install lambdabot/
branches:
  only:
    - master
