language: haskell
ghc:
  - 7.8
  - 7.6
install: cabal install happy --constraint="mtl==2.1.3.1"
script: .travis/build
branches:
  only:
    - master
notifications:
  irc: "chat.freenode.net#haskell-id"
